#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# NOT: Bu wizard bilinçli olarak write_env KULLANMAZ.
# Anahtar deposu parolası düz metin olarak repo içindeki .env'e yazılmamalı —
# tüm bu iş zaten "sırları repodan çıkarma" işiydi. Parola yalnız iki yere
# gider: (1) GitHub Actions secret'ı, (2) sizin parola yöneticiniz.

KEYSTORE_PATH="android/app/release.keystore"
REPO_SLUG="kadiryar571-eng/kuryemi-bul"

# Windows'ta keytool PATH'te olmayabilir — Android Studio'nun JBR'ını da dene.
# NOT: ${VAR:-} zorunlu — script `set -u` altında çalışıyor, JAVA_HOME
# tanımsızsa çıplak $JAVA_HOME "unbound variable" ile script'i öldürür.
find_keytool() {
  if command -v keytool >/dev/null 2>&1; then command -v keytool; return; fi
  local candidates=(
    "/c/Program Files/Android/Android Studio/jbr/bin/keytool.exe"
    "/c/Program Files/Android/Android Studio/jre/bin/keytool.exe"
    "/c/Program Files/Java/jdk-17/bin/keytool.exe"
    "/c/Program Files/Eclipse Adoptium/jdk-17/bin/keytool.exe"
  )
  [[ -n "${JAVA_HOME:-}" ]] && candidates+=("$JAVA_HOME/bin/keytool" "$JAVA_HOME/bin/keytool.exe")
  for c in "${candidates[@]}"; do
    [[ -x "$c" ]] && { printf '%s' "$c"; return; }
  done
  # Son çare: Program Files altında ara
  local found
  found=$(find "/c/Program Files" -maxdepth 5 -name "keytool.exe" -type f 2>/dev/null | head -1 || true)
  [[ -n "$found" ]] && { printf '%s' "$found"; return; }
  return 1
}

banner "KuryemiBul — Release imzalama anahtarı kurulumu"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Ön kontrol"
say "Gerekli araçları ve GitHub yetkinizi doğruluyoruz."

KEYTOOL=$(find_keytool) || {
  warn "keytool bulunamadı. Android Studio veya bir JDK 17 kurun."
  exit 1
}
printf '  %s✓%s keytool: %s\n' "$GREEN" "$RESET" "$KEYTOOL"

command -v gh >/dev/null 2>&1 || { warn "gh CLI kurulu değil: https://cli.github.com"; exit 1; }
printf '  %s✓%s gh CLI kurulu\n' "$GREEN" "$RESET"

# NOT: `|| true` şart — set -o pipefail altında grep eşleşme bulamazsa
# komut ikamesi hata döner ve set -e script'i sonlandırır.
ACTIVE_ACCT=$(gh auth status 2>&1 | grep -oE 'account [^ ]+' | head -1 | awk '{print $2}' || true)
note "aktif GitHub hesabı: ${ACTIVE_ACCT:-bilinmiyor}"

# Secret yazma iznini GERÇEKTEN test et — yanlış hesapla giriş yapılmış olabilir.
if ! gh secret list --repo "$REPO_SLUG" >/dev/null 2>&1; then
  printf '\n'
  warn "Aktif hesap ($ACTIVE_ACCT) $REPO_SLUG üzerinde secret yönetemiyor."
  say "Bu repo kadiryar571-eng'e ait. Doğru hesaba geçmeniz gerekiyor:"
  step "Zaten giriş yaptıysanız:  gh auth switch"
  step "Yapmadıysanız:            gh auth login"
  printf '\n'
  if confirm "Şimdi 'gh auth switch' çalıştırayım mı?"; then
    gh auth switch || true
  fi
  if ! gh secret list --repo "$REPO_SLUG" >/dev/null 2>&1; then
    warn "Hâlâ yetki yok. Secret'ları elle girmeniz gerekecek —"
    note "wizard devam edecek, sonunda değerleri size gösterecek."
    MANUAL_SECRETS=1
  fi
fi
pause "Devam etmek için Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Anahtar deposunu oluştur"
say "Bu, uygulamanızın kalıcı kimliğidir. Play Store'a yüklendikten sonra"
say "TÜM güncellemeler bu anahtarla imzalanmak zorundadır."
printf '\n'
warn "Kaybederseniz uygulamayı bir daha GÜNCELLEYEMEZSİNİZ."
note "Yeni paket adıyla sıfırdan yayınlamanız gerekir; kullanıcılar taşınmaz."
printf '\n'

if [[ -f "$KEYSTORE_PATH" ]]; then
  warn "$KEYSTORE_PATH zaten var."
  confirm "ÜZERİNE YAZILSIN MI? (eski anahtar kalıcı olarak kaybolur)" || {
    say "Mevcut anahtar korundu. Parolasını girerek secret'ları yenileyebilirsiniz."
    KEEP_EXISTING=1
  }
fi

ask KEY_ALIAS "Anahtar takma adı [kuryemibul]:"
[[ -z "$KEY_ALIAS" ]] && KEY_ALIAS="kuryemibul"

printf '\n'
say "Parola en az 12 karakter olsun. Parola yöneticinize KAYDEDİN —"
say "bu ekrandan sonra hiçbir yerde düz metin saklanmayacak."
while :; do
  ask_secret KS_PASS "Anahtar deposu parolası:"
  [[ ${#KS_PASS} -lt 6 ]] && { warn "çok kısa, tekrar deneyin"; continue; }
  ask_secret KS_PASS2 "Parolayı tekrar girin:"
  [[ "$KS_PASS" == "$KS_PASS2" ]] && break
  warn "parolalar eşleşmedi, tekrar deneyin"
done

if [[ -z "${KEEP_EXISTING:-}" ]]; then
  printf '\n'
  say "Sertifika bilgileri (kullanıcıya görünmez, sonradan değiştirilemez):"
  ask CERT_CN "Ad Soyad / Kurum [KuryemiBul]:"
  [[ -z "$CERT_CN" ]] && CERT_CN="KuryemiBul"
  ask CERT_CITY "Şehir [Istanbul]:"
  [[ -z "$CERT_CITY" ]] && CERT_CITY="Istanbul"

  printf '\n'
  say "Anahtar üretiliyor (4096-bit RSA, 10000 gün geçerli)..."
  rm -f "$KEYSTORE_PATH"
  "$KEYTOOL" -genkeypair -v \
    -keystore "$KEYSTORE_PATH" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10000 \
    -storetype PKCS12 \
    -storepass "$KS_PASS" -keypass "$KS_PASS" \
    -dname "CN=$CERT_CN, O=$CERT_CN, L=$CERT_CITY, C=TR" \
    >/dev/null 2>&1 || { warn "keytool başarısız oldu"; exit 1; }
  printf '  %s✓%s oluşturuldu: %s\n' "$GREEN" "$RESET" "$KEYSTORE_PATH"
fi

# Parolanın gerçekten çalıştığını doğrula (yanlış parolayla secret yazmayalım)
if ! "$KEYTOOL" -list -keystore "$KEYSTORE_PATH" -storepass "$KS_PASS" >/dev/null 2>&1; then
  warn "Parola bu anahtar deposunu açmıyor. Baştan çalıştırın."
  exit 1
fi
printf '  %s✓%s parola doğrulandı\n' "$GREEN" "$RESET"
pause "Devam etmek için Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "GitHub Actions secret'larını yaz"
say "CI'ın imzalı APK üretebilmesi için dört değer gerekiyor."
printf '\n'

KS_B64=$(base64 -w0 "$KEYSTORE_PATH" 2>/dev/null || base64 "$KEYSTORE_PATH" | tr -d '\n')
note "keystore base64'e çevrildi (${#KS_B64} karakter)"
printf '\n'

if [[ -z "${MANUAL_SECRETS:-}" ]]; then
  set_secret KEYSTORE_BASE64   "$KS_B64"
  set_secret KEYSTORE_PASSWORD "$KS_PASS"
  set_secret KEY_ALIAS         "$KEY_ALIAS"
  set_secret KEY_PASSWORD      "$KS_PASS"   # PKCS12'de depo parolasıyla aynı
else
  warn "gh yetkisi yok — bu dördünü elle ekleyin:"
  open_url "https://github.com/$REPO_SLUG/settings/secrets/actions"
  printf '\n'
  say "KEY_ALIAS         = $KEY_ALIAS"
  say "KEYSTORE_PASSWORD = (az önce girdiğiniz parola)"
  say "KEY_PASSWORD      = (aynı parola)"
  say "KEYSTORE_BASE64   = aşağıdaki dosyanın içeriği:"
  printf '%s' "$KS_B64" > keystore.base64.txt
  note "  → keystore.base64.txt (kopyaladıktan sonra SİLİN)"
  SKIPPED+=("keystore.base64.txt dosyasını silin")
fi
pause "Devam etmek için Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Yedekleme ve doğrulama"

# Anahtarın kazara commit'lenmediğini garanti et
if git check-ignore -q "$KEYSTORE_PATH" 2>/dev/null; then
  printf '  %s✓%s %s .gitignore tarafından korunuyor\n' "$GREEN" "$RESET" "$KEYSTORE_PATH"
else
  warn "$KEYSTORE_PATH .gitignore'da DEĞİL — repoya sızabilir!"
  SKIPPED+=(".gitignore'a *.keystore ekleyin")
fi

if [[ -z "${MANUAL_SECRETS:-}" ]]; then
  printf '\n'; say "Yazılan secret'lar:"
  gh secret list --repo "$REPO_SLUG" 2>/dev/null | sed 's/^/    /' || true
fi

printf '\n'
warn "ŞİMDİ YAPIN — bu adım atlanırsa uygulamayı güncelleyemezsiniz:"
step "$KEYSTORE_PATH dosyasını iki ayrı güvenli yere kopyalayın"
step "Parolayı parola yöneticinize kaydedin"
step "Play Console'da 'Play App Signing'i etkinleştirin (Google yedeğinizi tutar)"
printf '\n'
say "Sonra derlemeyi başlatın:"
note "  gh workflow run android.yml   —veya—   Actions sekmesinden 'Run workflow'"

finish
